### PR TITLE
Bug Fix Branch: Fixes issue 61

### LINKED ISSUE #61: Android: App crashes when getExternalFilesDir() returns null
Hi,

I noticed that sometimes getExternalFilesDir() returns null, and then the app crashes.

Java exception in 'NativeModules' java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getParentFile()' on a null object reference, stack: com.RNFetchBlob.RNFetchBlobFS.getSystemfolders@216 com.RNFetchBlob.RNFetchBlob.getConstants@84 com.facebook.react.bridge.JavaModuleWrapper.getConstants@140 android.os.Handler.handleCallback@751 android.os.Handler.dispatchMessage@95 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage@31

I can reproduce it when I'm on Android 4.3 or below, but in production (we have an app with +/- 1 million installs) we hit this error on all kind of Android versions.

Best,
Nicolas

### PR DESCRIPTION
**Pull request by poison**
This fixes #61

### CODE REVIEW

**Comment by Gideon877** [comment]
Hey guys, any idea of when is this being released? We are experiencing this issue.

@poison @chrusart @ssedrick @Traviskn @tslater

**Comment by ssedrick** [comment]
@Gideon877 We just pushed out a release under a new name. Please try installing rn-fetch-blob from npm. If you continue to experience this issue, please let us know or open a pull request.

**Comment by Jeijie** [comment]
same issue, the version is 0.10.9

**Comment by Jeijie** [comment]
same issue ,the version is 0.10.12

**Pull request merged**
